
@isTest
private class OrderBeforeUpdateTriggerTest {

    @isTest
    static void test01_singleAction() {
        // TO DO: implement unit test
    }

    @isTest
    static void test02_bulkActions() {
        // TO DO: implement unit test
    }

    @isTest
    static void test03_positiveBehaviour() {
        // TO DO: implement unit test
    }

    @isTest
    static void test04_negativeBehaviour() {
        // TO DO: implement unit test
    }

     @isTest
    static void test05_restrictedUser() {
        // TO DO: implement unit test
    }

    

}